name: yopee_cleaner
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-210.3.beta <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.8
  provider: ^6.0.5
  http: ^0.13.6
  cached_network_image:
  path: ^1.8.3
  dio:
  file_picker: ^6.1.1


  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  geocoding: ^2.0.4
  dots_indicator: ^3.0.0
  carousel_slider: ^4.0.0
  fluttertoast: ^8.2.2
  flutter_html:

  google_places_flutter:
  image_picker:
  intl:
  flutter_rating_bar: ^4.0.1
  datepicker_dropdown: ^0.0.9
  expansion_tile_card: ^3.0.0
  flutter_slimy_card: ^1.0.2
  number_paginator: ^0.4.0
  pager: ^0.0.3
  url_launcher:
  change_app_package_name: ^1.1.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_file_downloader: ^1.2.1
  downloads_path_provider_28: ^0.1.2
  permission_handler: ^8.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/images/login/car-washing.png
    - assets/images/login/login_backgnd.png
    - assets/images/login/phone-icon.svg
    - assets/images/login/phone-icon.png
    - assets/images/splash/bg.png
    - assets/images/splash/yopee_logo.png
    - assets/images/arrow-white.svg
    - assets/images/arrow-left-solid.svg
    - assets/images/map-marker.svg
    - assets/images/search.svg
    - assets/images/dashboard/Complete.svg
    - assets/images/dashboard/exterior.png
    - assets/images/dashboard/headlight.png
    - assets/images/dashboard/history.svg
    - assets/images/dashboard/home.svg
    - assets/images/dashboard/interior.png
    - assets/images/dashboard/interior_detailing.png
    - assets/images/dashboard/Page.svg
    - assets/images/dashboard/paint.png
    - assets/images/dashboard/steaming.png
    - assets/images/dashboard/car-solid.svg
    - assets/images/cancel.png
    - assets/images/edit.png
    - assets/images/share.png
    - assets/images/addAddress.png
    - assets/images/yopeeicon.png
    - assets/images/detailing_service.png
    - assets/images/exterior_service.png
    - assets/images/interior_service.png
    - assets/images/face-smile-regular.svg
    - assets/images/clock-regular.svg
    - assets/images/addVehicle/car-1.png
    - assets/images/addVehicle/car-2.png
    - assets/images/addVehicle/car-3.png
    - assets/images/addVehicle/car-4.png
    - assets/images/addVehicle/car-5.png
    - assets/images/addVehicle/car-6.png
    - assets/images/addVehicle/car-7.png
    - assets/images/carBrand/Audi.png
    - assets/images/carBrand/BMW.png
    - assets/images/carBrand/Citrogen.png
    - assets/images/carBrand/Honda.png
    - assets/images/carBrand/Hyundai.png
    - assets/images/carBrand/Mahindra.png
    - assets/images/carBrand/Mercedes.png
    - assets/images/carBrand/MG_Motors.png
    - assets/images/carBrand/Nissan.png
    - assets/images/carBrand/Renault.png
    - assets/images/carBrand/Suzuki.png
    - assets/images/carBrand/Tata.png
    - assets/images/carBrand/Toyota.png
    - assets/images/carBrand/Volkswagen.png
    - assets/images/carBrand/Volvo.png
    - assets/images/circle_green.svg
    - assets/images/menu/angle-right.svg
    - assets/images/menu/bell.svg
    - assets/images/menu/Complete.svg
    - assets/images/menu/profile.png
    - assets/images/menu/share.svg
    - assets/images/menu/subscription.svg
    - assets/images/menu/user-check.svg
    - assets/images/menu/wash-hands.svg
    - assets/images/menu/edit.svg
    - assets/images/notification/blue_tick.svg
    - assets/images/notification/delete-icon.svg
    - assets/images/notification/green_tick.svg
    - assets/images/notification/off-toggle.svg
    - assets/images/notification/red_tick.svg
    - assets/images/notification/toggle.svg
    - assets/images/phone-calling.svg
    - assets/images/envelope.svg
    - assets/images/calendar-days-regular.svg
    - assets/images/pngwing.com.png
    - assets/images/cancel_circle.svg
    - assets/images/edit.svg
    - assets/images/subscription/special_pkg.svg
    - assets/images/subscription/silver_pkg.svg
    - assets/images/subscription/gold_pkg.svg
    - assets/images/check-solid.svg
    - assets/images/toggle.png
    - assets/images/money-bag.png
    - assets/images/monthly.png
    - assets/images/rating.png
    - assets/images/request.png
    - assets/images/today.png
    - assets/images/bell.svg
    - assets/images/call.svg
    - assets/images/indian-rupee.svg
    - assets/images/contact-us.svg
    - assets/images/calendar.png
    - assets/images/kyc.svg
    - assets/images/feedback.svg
    - assets/images/task.svg
    - assets/images/earning/car.png
    - assets/images/earning/car-service.png
    - assets/images/earning/earning-icon.png
    - assets/images/earning/earning-icon-6.png
    - assets/images/earning/exchange.png
    - assets/images/trash-can-regular.svg
    - assets/images/toggle-active.svg
    - assets/images/logout.svg
    - assets/images/unread.svg
    - assets/images/read.svg
    - assets/images/add-plus.svg
    - assets/images/Close.svg
    - assets/images/alarm-clock.svg
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: PoppinsBlack
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
    - family: PoppinsBlackItalic
      fonts:
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
    - family: PoppinsBoldItalic
      fonts:
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
    - family: PoppinsExtraBoldItalic
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
    - family: PoppinsExtraLight
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
    - family: PoppinsExtraLightItalic
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
    - family: PoppinsItalic
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
    - family: PoppinsLightItalic
      fonts:
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
    - family: PoppinsMediumItalic
      fonts:
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
    - family: PoppinsSemiBoldItalic
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
    - family: PoppinsThin
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
    - family: PoppinsThinItalic
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
    - family: Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
    - family: BlackItalic
      fonts:
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: BoldItalic
      fonts:
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - family: ExtraBoldItalic
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
    - family: ExtraLight
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
    - family: ExtraLightItalic
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
    - family: Italic
      fonts:
        - asset: assets/fonts/Montserrat-Italic.ttf
    - family: Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: LightItalic
      fonts:
        - asset: assets/fonts/Montserrat-LightItalic.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MediumItalic
      fonts:
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: SemiBoldItalic
      fonts:
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
    - family: Thin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
    - family: ThinItalic
      fonts:
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
